### PR TITLE
Added land map from landlord

### PR DESCRIPTION
**Pull request by SpatiumPrinceps**
Hey there, 
I found this plugin really interesting but it really needs landlords landmap. 
Since landlords codebase is somewhat unmaintained, and I dont have the time to rewrite the entire thingy, I just implemented the landmap into cubit. 
Now its almost identically in terms of features, but cubit seems to be way more stable. 
You can have a look at the landmap here: https://proxy.spigotmc.org/389ad549f344a0ba237fa8fbeb5ffb58ce4be1cc?url=http%3A%2F%2Fi.imgur.com%2F1VrUtMol.png

Have a nice day!

EDIT: Probably need a final touch in terms of language strings and a boolean in config to disable the map

### CODE REVIEW

**Comment by LinzN** [comment]
I add the language code today in the evening. Thanks again ;)

**Comment by SpatiumPrinceps** [comment]
Since the pull request I have worked hours on the land map and noticed some issues. 
Do you know how well worldguard caches regions? 
The thing is: Landmap updates almost 3 times a second, and pulls every update 7*7 lands from the database. In an unoptimized enviroment thats 150 database lookups per second per player. 
In landlord I implemented an advanced caching system with guava, and optimized the map by reducing the refreshrate of the scoreboard to one second and rewriting the way the map interacts with the database. In the pullrequest I made the plugins asks worldguard for every "partial" land of the landmap, while you can reduce this to just one lookup as seen here in this mysql query (at the very bottom): https://github.com/SpatiumPrinceps/LandLord/blob/master/src/main/java/com/jcdesimp/landlord/persistantData/db/MySQLDatabase.java
Dunno, it depends on worldguard. Never really worked with worldguard, just wanted to tell you there might be a performance issue :D

**Comment by LinzN** [comment]
Hey, yes i know what you mean. But i think there is a solution. WorldGuard has a cache system. But i must look how it works in the next days. It is now possible to activate/deactivate this feature in the Setting.yml.
The default value is false until it works with the cache system. Thank you again for this nice feature :D

**Comment by SpatiumPrinceps** [comment]
Your welcome :) There is one little thing you should remove: the field nearbyLands in LandMap is currently useless, just taking some computationtime without being involved in the actual process. Its a relict from the old dev which I forgot to remove ;) 
Just delete everything concerning the nearbyLand list (especially that part in the update method sucks some computation time).. :D

**Comment by LinzN** [comment]
Hey, yes there is some useless code. I clean up this between the next days. :D

**Pull request merged**
